version: 2
jobs:
  build:
    docker:
      - image: dockercore/golang-cross:1.9.5
    environment:
      http_proxy: http://proxy-infra.frg.tech:3128
      https_proxy: http://proxy-infra.frg.tech:3128
      no_proxy: 127.0.0.1,repo.frg.tech
      ARTIFACTORY_URL: http://repo.frg.tech/artifactory/cloud/
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - checkout
      - run:
          name: Config Environment
          command: |
            echo 'Config Environment' > $BASH_ENV
      - run:
          name: test
          command: |
            make test
      - deploy:
          name: deploy
          command: |
            make build
            ARTIFACT_NAME="terraform-provider-phpipam"
            curl -fSs -u${artifactory_user_id}:${artifactory_password} -T ./pkg/darwin_amd64/${ARTIFACT_NAME} "${ARTIFACTORY_URL}/${CIRCLE_PROJECT_REPONAME}/pkg/darwin_amd64/${ARTIFACT_NAME};branch=${CIRCLE_BRANCH}"
            curl -fSs -u${artifactory_user_id}:${artifactory_password} -T ./pkg/linux_amd64/${ARTIFACT_NAME} "${ARTIFACTORY_URL}/${CIRCLE_PROJECT_REPONAME}/pkg/linux_amd64/${ARTIFACT_NAME};branch=${CIRCLE_BRANCH}"
            curl -fSs -u${artifactory_user_id}:${artifactory_password} -T ./pkg/windows_amd64/${ARTIFACT_NAME} "${ARTIFACTORY_URL}/${CIRCLE_PROJECT_REPONAME}/pkg/windows_amd64/${ARTIFACT_NAME};branch=${CIRCLE_BRANCH}"
            # python -m kioskbucket > template.json
            # if [[ ${CIRCLE_BRANCH} == "master" ]]; then VERSION=1.0.${CIRCLE_BUILD_NUM}
            # else VERSION=1.0-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
            # fi;
            # TEMPLATE_DIR=${CIRCLE_PROJECT_REPONAME}-${VERSION};
            # mkdir ${TEMPLATE_DIR};
            # mv template.json ${TEMPLATE_DIR}/;
            # ARTIFACT_NAME=${TEMPLATE_DIR}.tgz;
            # tar cvzf ${ARTIFACT_NAME} ${TEMPLATE_DIR};
            # curl -fSs -u${artifactory_user_id}:${artifactory_password} -T ./${ARTIFACT_NAME} "${ARTIFACTORY_URL}/${CIRCLE_PROJECT_REPONAME}/${ARTIFACT_NAME};branch=${CIRCLE_BRANCH}"

